---
name: Build and Push Golang Image to AWS ECR
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli


    - name: Configure AWS credentials
      run:
        creds=($(aws sts assume-role --region ${AWS_REGION} --role-arn ${{ secrets.AWS_ASSUME_ROLE_ARN }} --role-session-name "GitHubActionsSession-132904414" --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text))
        export AWS_ACCESS_KEY_ID=${creds[0]}
        export AWS_SECRET_ACCESS_KEY=${creds[1]}
        export AWS_SESSION_TOKEN=${creds[2]} 
      
    - name: Login to Amazon ECR
      id : login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: false
        registry-type: private
        skip-logout: false

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./build/git_update.sh -v major

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: test-demo
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
